-- Create messages table if it doesn't exist
create table if not exists messages (
    id bigint generated by default as identity primary key,
    content text not null,
    timestamp timestamptz default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table messages enable row level security;

-- Drop existing policies if they exist
drop policy if exists "Anyone can read messages" on messages;
drop policy if exists "Anyone can insert messages" on messages;

-- Create policies
create policy "Anyone can read messages"
    on messages
    for select
    using (true);

create policy "Anyone can insert messages"
    on messages
    for insert
    with check (true);

-- Enable realtime
begin;
    drop publication if exists supabase_realtime;
    create publication supabase_realtime;
commit;

alter publication supabase_realtime add table messages;
